##########################################################################
# This file is centrally managed, any manual changes will be OVERWRITTEN #
##########################################################################
---
master:
  facts:
    terminus: puppetdb
    cache: yaml
